# Generated by Django 5.1.1 on 2024-09-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='importance',
            field=models.IntegerField(choices=[(1, 'Not Important'), (2, 'Important')], default=1),
        ),
        migrations.AddField(
            model_name='job',
            name='urgency',
            field=models.IntegerField(choices=[(1, 'Not Urgent'), (2, 'Urgent')], default=1),
        ),
    ]
